name: musified
description: Premium iOS Streaming App with YouTube Music & JioSaavn Lossless Audio
homepage: https://github.com/tinyredphoenix/Musified
repository: https://github.com/tinyredphoenix/Musified
issue_tracker: https://github.com/tinyredphoenix/Musified/issues

publish_to: 'none'
version: 1.9.0+31

environment:
  sdk: '>=3.12.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  app_links: ^7.2.1
  audio_service: ^0.18.19
  audio_session: ^0.2.4
  cached_network_image: ^3.4.1
  crypto: ^3.0.6
  cupertino_icons: ^1.0.8
  dart_des: ^1.0.2
  file_picker: ^12.0.0
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.4.1
  flutter_localizations:
    sdk: flutter
  go_router: ^17.5.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  html: ^0.15.6
  http: ^1.6.0
  intl: ^0.20.2
  just_audio: ^0.10.6
  path_provider: ^2.1.6
  rxdart: ^0.28.0
  share_plus: ^13.3.0
  url_launcher: ^6.3.2
  webview_flutter: ^4.12.0
  youtube_explode_dart:
    path: ./packages/youtube_explode_dart
  youtube_music_explode_dart:
    path: ./packages/youtube_music_explode_dart
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/licenses/
    - assets/icons/musify_icon.png

  fonts:
    - family: paytoneOne
      fonts:
        - asset: assets/fonts/paytone/PaytoneOne-Regular.ttf
